#!/usr/bin/env python3
"""Create publication-ready figures from NaPF6 ion-pairing analysis CSVs.

This command does not read or modify trajectories. It consumes outputs from
analyze_ion_pairing.py and writes figures into that same analysis directory.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
import sys
from typing import Sequence


DEFAULT_ANALYSIS_SUBDIR = "analysis_ion_pairing"
DEFAULT_PRIMARY_CUTOFF_NM = 0.5
DEFAULT_DPI = 300
PLOT_STEMS = (
    "figure_Na_P_rdf_cn",
    "figure_Na_F_rdf_cn",
    "figure_ion_pairing_primary",
    "figure_ion_pairing_cutoff_sensitivity",
    "figure_ion_pairing_timeseries",
)
COLORS = {
    "rdf": "#0072B2",
    "cn": "#D55E00",
    "SIP/SSIP": "#56B4E9",
    "CIP": "#009E73",
    "AGG": "#CC79A7",
    "primary": "#222222",
    "minimum": "#E69F00",
}


class PlotError(RuntimeError):
    """Raised for missing, malformed, or incompatible analysis output."""


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Plot Na-P/Na-F RDF and CN data plus SIP/CIP/AGG populations. "
            "Figures remain inside the selected analysis directory."
        )
    )
    location = parser.add_mutually_exclusive_group(required=True)
    location.add_argument(
        "--case-label",
        help="Case label below --cases-root.",
    )
    location.add_argument(
        "--case-dir",
        type=Path,
        help="Path to a generated case directory.",
    )
    location.add_argument(
        "--analysis-dir",
        type=Path,
        help="Path directly to an analysis_ion_pairing directory.",
    )
    parser.add_argument(
        "--cases-root",
        type=Path,
        help="Cases directory; defaults to the cases folder beside this script.",
    )
    parser.add_argument(
        "--analysis-subdir",
        default=DEFAULT_ANALYSIS_SUBDIR,
        help=f"Analysis folder within a case (default: {DEFAULT_ANALYSIS_SUBDIR}).",
    )
    parser.add_argument(
        "--primary-cutoff-nm",
        type=positive_float,
        help="Override the primary cutoff recorded in analysis_manifest.json.",
    )
    parser.add_argument(
        "--format",
        dest="formats",
        action="append",
        choices=("png", "svg", "pdf"),
        help="Output format; repeat for multiple formats (default: png).",
    )
    parser.add_argument(
        "--dpi",
        type=positive_int,
        default=DEFAULT_DPI,
        help=f"Raster resolution for PNG output (default: {DEFAULT_DPI}).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing graph files generated by this command.",
    )
    return parser.parse_args(argv)


def positive_float(value: str) -> float:
    parsed = float(value)
    if not math.isfinite(parsed) or parsed <= 0:
        raise argparse.ArgumentTypeError("value must be a positive finite number")
    return parsed


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("value must be a positive integer")
    return parsed


def resolve_analysis_dir(args: argparse.Namespace) -> Path:
    script_root = Path(__file__).resolve().parent
    if Path(args.analysis_subdir).name != args.analysis_subdir:
        raise PlotError("--analysis-subdir must be a single directory name")

    if args.analysis_dir is not None:
        analysis_dir = args.analysis_dir.expanduser().resolve()
    elif args.case_dir is not None:
        case_dir = args.case_dir.expanduser().resolve()
        analysis_dir = (case_dir / args.analysis_subdir).resolve()
    else:
        cases_root = (args.cases_root or script_root / "cases").resolve()
        case_dir = (cases_root / args.case_label).resolve()
        if case_dir.parent != cases_root:
            raise PlotError("--case-label must name one direct child of --cases-root")
        analysis_dir = (case_dir / args.analysis_subdir).resolve()

    if not analysis_dir.is_dir():
        raise PlotError(f"Analysis directory does not exist: {analysis_dir}")
    return analysis_dir


def require_file(analysis_dir: Path, name: str) -> Path:
    path = analysis_dir / name
    if not path.is_file():
        raise PlotError(
            f"Required analysis file is missing: {path}\n"
            "Run analyze_ion_pairing.py successfully before plotting."
        )
    return path


def read_numeric_csv(path: Path, required_columns: Sequence[str]) -> list[dict[str, float]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        headers = reader.fieldnames or []
        missing = [column for column in required_columns if column not in headers]
        if missing:
            raise PlotError(f"Missing columns in {path}: {', '.join(missing)}")
        rows: list[dict[str, float]] = []
        for line_number, raw_row in enumerate(reader, start=2):
            try:
                rows.append(
                    {
                        column: float(raw_row[column])
                        for column in required_columns
                    }
                )
            except (TypeError, ValueError) as exc:
                raise PlotError(
                    f"Non-numeric value in {path} at CSV line {line_number}"
                ) from exc
    if not rows:
        raise PlotError(f"No data rows found in {path}")
    return rows


def read_manifest(analysis_dir: Path) -> dict[str, object]:
    path = analysis_dir / "analysis_manifest.json"
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        raise PlotError(f"Could not read analysis manifest: {path}") from exc


def nested_value(mapping: dict[str, object], *keys: str) -> object | None:
    value: object = mapping
    for key in keys:
        if not isinstance(value, dict) or key not in value:
            return None
        value = value[key]
    return value


def primary_cutoff(args: argparse.Namespace, manifest: dict[str, object]) -> float:
    if args.primary_cutoff_nm is not None:
        return args.primary_cutoff_nm
    value = nested_value(manifest, "classification", "primary_cutoff_nm")
    if isinstance(value, (int, float)) and math.isfinite(float(value)):
        return float(value)
    return DEFAULT_PRIMARY_CUTOFF_NM


def select_cutoff_rows(
    rows: Sequence[dict[str, float]], cutoff_nm: float
) -> list[dict[str, float]]:
    selected = [
        row
        for row in rows
        if math.isclose(row["cutoff_nm"], cutoff_nm, abs_tol=1e-9)
    ]
    if not selected:
        available = sorted({row["cutoff_nm"] for row in rows})
        rendered = ", ".join(f"{value:g}" for value in available)
        raise PlotError(
            f"Primary cutoff {cutoff_nm:g} nm is not present; available: {rendered}"
        )
    return selected


def moving_average(values: Sequence[float], window: int) -> list[float]:
    if not values:
        return []
    window = max(1, min(window, len(values)))
    half = window // 2
    result = []
    for index in range(len(values)):
        start = max(0, index - half)
        end = min(len(values), index + half + 1)
        result.append(sum(values[start:end]) / (end - start))
    return result


def load_matplotlib():
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise PlotError(
            "Matplotlib is required for graphing. Install it with:\n"
            "  python3 -m pip install matplotlib"
        ) from exc
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.size": 10,
            "axes.labelsize": 11,
            "axes.titlesize": 12,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "legend.frameon": False,
            "figure.dpi": 120,
            "savefig.facecolor": "white",
        }
    )
    return plt


def output_paths(
    analysis_dir: Path, formats: Sequence[str]
) -> list[Path]:
    return [analysis_dir / f"{stem}.{extension}" for stem in PLOT_STEMS for extension in formats]


def guard_outputs(paths: Sequence[Path], force: bool) -> None:
    existing = [path for path in paths if path.exists()]
    if existing and not force:
        rendered = "\n".join(f"  {path}" for path in existing)
        raise PlotError(
            "Graph output already exists:\n"
            f"{rendered}\nUse --force to overwrite graph files."
        )


def save_figure(fig, analysis_dir: Path, stem: str, formats: Sequence[str], dpi: int) -> list[Path]:
    saved = []
    for extension in formats:
        path = analysis_dir / f"{stem}.{extension}"
        kwargs = {"bbox_inches": "tight"}
        if extension == "png":
            kwargs["dpi"] = dpi
        fig.savefig(path, **kwargs)
        saved.append(path)
    return saved


def plot_rdf_cn(
    plt,
    rows: Sequence[dict[str, float]],
    pair_label: str,
    case_label: str,
    primary_nm: float,
    detected_minimum_nm: float | None,
):
    fig, axes = plt.subplots(
        2,
        1,
        figsize=(7.2, 6.2),
        sharex=True,
        gridspec_kw={"height_ratios": (1.15, 1.0), "hspace": 0.08},
    )
    radii = [row["rdf_r_nm"] for row in rows]
    g_values = [row["g_r"] for row in rows]
    cn_radii = [row["cn_r_nm"] for row in rows]
    cn_values = [row["running_coordination_number"] for row in rows]

    axes[0].plot(radii, g_values, color=COLORS["rdf"], linewidth=1.8)
    axes[0].set_ylabel(r"RDF, $g(r)$")
    axes[0].set_title(f"{case_label}: {pair_label} radial distribution")
    axes[1].plot(cn_radii, cn_values, color=COLORS["cn"], linewidth=1.8)
    axes[1].set_ylabel(r"Running CN, $N(r)$")
    axes[1].set_xlabel("Distance, r (nm)")

    for axis in axes:
        axis.grid(True, color="#D9D9D9", linewidth=0.6, alpha=0.7)
        if pair_label == "Na-P":
            axis.axvline(
                primary_nm,
                color=COLORS["primary"],
                linestyle="--",
                linewidth=1.1,
                label=f"Primary cutoff ({primary_nm:g} nm)",
            )
            if detected_minimum_nm is not None:
                axis.axvline(
                    detected_minimum_nm,
                    color=COLORS["minimum"],
                    linestyle=":",
                    linewidth=1.3,
                    label=f"Automatic local minimum ({detected_minimum_nm:g} nm)",
                )
    if pair_label == "Na-P":
        axes[0].legend(loc="upper right")
    fig.align_ylabels(axes)
    return fig


def plot_primary_populations(plt, row: dict[str, float], case_label: str):
    labels = ["SIP/SSIP", "CIP", "AGG"]
    values = [
        100 * row["sip_ssip_fraction"],
        100 * row["cip_fraction"],
        100 * row["agg_fraction"],
    ]
    errors = [
        100 * row["sip_ssip_block_standard_error"],
        100 * row["cip_block_standard_error"],
        100 * row["agg_block_standard_error"],
    ]
    fig, axis = plt.subplots(figsize=(6.6, 4.8))
    bars = axis.bar(
        labels,
        values,
        yerr=errors,
        capsize=4,
        color=[COLORS[label] for label in labels],
        edgecolor="#333333",
        linewidth=0.7,
    )
    axis.set_ylabel("Na environments (%)")
    axis.set_ylim(0, max(55, max(value + error for value, error in zip(values, errors)) + 8))
    axis.set_title(
        f"{case_label}: ion-pairing populations at {row['cutoff_nm']:g} nm"
    )
    axis.grid(True, axis="y", color="#D9D9D9", linewidth=0.6, alpha=0.7)
    for bar, value in zip(bars, values):
        axis.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 1.2,
            f"{value:.1f}%",
            ha="center",
            va="bottom",
        )
    fig.tight_layout()
    return fig


def plot_cutoff_sensitivity(plt, rows: Sequence[dict[str, float]], case_label: str, primary_nm: float):
    ordered = sorted(rows, key=lambda row: row["cutoff_nm"])
    cutoffs = [row["cutoff_nm"] for row in ordered]
    series = {
        "SIP/SSIP": ("sip_ssip_fraction", "sip_ssip_block_standard_error"),
        "CIP": ("cip_fraction", "cip_block_standard_error"),
        "AGG": ("agg_fraction", "agg_block_standard_error"),
    }
    fig, axis = plt.subplots(figsize=(7.2, 4.9))
    for label, (fraction_key, error_key) in series.items():
        axis.errorbar(
            cutoffs,
            [100 * row[fraction_key] for row in ordered],
            yerr=[100 * row[error_key] for row in ordered],
            marker="o",
            markersize=4.5,
            linewidth=1.7,
            capsize=3,
            color=COLORS[label],
            label=label,
        )
    axis.axvline(
        primary_nm,
        color=COLORS["primary"],
        linestyle="--",
        linewidth=1.1,
        label=f"Primary ({primary_nm:g} nm)",
    )
    axis.set_xlabel("Na-P cutoff (nm)")
    axis.set_ylabel("Na environments (%)")
    axis.set_title(f"{case_label}: cutoff sensitivity")
    axis.grid(True, color="#D9D9D9", linewidth=0.6, alpha=0.7)
    axis.legend(ncol=2)
    fig.tight_layout()
    return fig


def plot_timeseries(plt, rows: Sequence[dict[str, float]], case_label: str, cutoff_nm: float):
    ordered = sorted(rows, key=lambda row: row["time_ps"])
    times_ns = [row["time_ps"] / 1000 for row in ordered]
    window = max(3, len(ordered) // 20)
    series = {
        "SIP/SSIP": "sip_ssip_fraction",
        "CIP": "cip_fraction",
        "AGG": "agg_fraction",
    }
    fig, axis = plt.subplots(figsize=(7.5, 4.9))
    all_raw_values: list[float] = []
    for label, key in series.items():
        raw = [100 * row[key] for row in ordered]
        all_raw_values.extend(raw)
        smoothed = moving_average(raw, window)
        axis.plot(times_ns, raw, color=COLORS[label], linewidth=0.5, alpha=0.20)
        axis.plot(
            times_ns,
            smoothed,
            color=COLORS[label],
            linewidth=1.8,
            label=f"{label} ({window}-frame mean)",
        )
    axis.set_xlabel("Time (ns)")
    axis.set_ylabel("Na environments (%)")
    axis.set_ylim(0, min(100, max(60, max(all_raw_values) + 5)))
    axis.set_title(f"{case_label}: population convergence at {cutoff_nm:g} nm")
    axis.grid(True, color="#D9D9D9", linewidth=0.6, alpha=0.7)
    axis.legend(ncol=1)
    fig.tight_layout()
    return fig, window


def case_label_from_manifest(manifest: dict[str, object], analysis_dir: Path) -> str:
    label = manifest.get("case_label")
    if isinstance(label, str) and label:
        return label
    return analysis_dir.parent.name


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    analysis_dir = resolve_analysis_dir(args)
    formats = list(dict.fromkeys(args.formats or ["png"]))
    manifest = read_manifest(analysis_dir)
    cutoff_nm = primary_cutoff(args, manifest)
    case_label = case_label_from_manifest(manifest, analysis_dir)

    rdf_columns = (
        "rdf_r_nm",
        "g_r",
        "cn_r_nm",
        "running_coordination_number",
    )
    summary_columns = (
        "cutoff_nm",
        "sip_ssip_fraction",
        "sip_ssip_block_standard_error",
        "cip_fraction",
        "cip_block_standard_error",
        "agg_fraction",
        "agg_block_standard_error",
    )
    timeseries_columns = (
        "time_ps",
        "cutoff_nm",
        "sip_ssip_fraction",
        "cip_fraction",
        "agg_fraction",
    )
    na_p_rows = read_numeric_csv(
        require_file(analysis_dir, "rdf_coordination_Na_P.csv"), rdf_columns
    )
    na_f_rows = read_numeric_csv(
        require_file(analysis_dir, "rdf_coordination_Na_F.csv"), rdf_columns
    )
    summary_rows = read_numeric_csv(
        require_file(analysis_dir, "ion_pairing_summary.csv"), summary_columns
    )
    timeseries_rows = read_numeric_csv(
        require_file(analysis_dir, "ion_pairing_timeseries.csv"),
        timeseries_columns,
    )
    primary_summary = select_cutoff_rows(summary_rows, cutoff_nm)[0]
    primary_timeseries = select_cutoff_rows(timeseries_rows, cutoff_nm)

    planned_outputs = output_paths(analysis_dir, formats)
    plot_manifest_path = analysis_dir / "plot_manifest.json"
    guard_outputs([*planned_outputs, plot_manifest_path], args.force)
    plt = load_matplotlib()

    detected = nested_value(
        manifest, "rdf", "na_p_first_peak_and_minimum", "minimum_r_nm"
    )
    detected_minimum_nm = (
        float(detected) if isinstance(detected, (int, float)) else None
    )
    saved: list[Path] = []
    figures = [
        (
            "figure_Na_P_rdf_cn",
            plot_rdf_cn(
                plt,
                na_p_rows,
                "Na-P",
                case_label,
                cutoff_nm,
                detected_minimum_nm,
            ),
        ),
        (
            "figure_Na_F_rdf_cn",
            plot_rdf_cn(
                plt, na_f_rows, "Na-F", case_label, cutoff_nm, None
            ),
        ),
        (
            "figure_ion_pairing_primary",
            plot_primary_populations(plt, primary_summary, case_label),
        ),
        (
            "figure_ion_pairing_cutoff_sensitivity",
            plot_cutoff_sensitivity(plt, summary_rows, case_label, cutoff_nm),
        ),
    ]
    timeseries_figure, moving_window = plot_timeseries(
        plt, primary_timeseries, case_label, cutoff_nm
    )
    figures.append(("figure_ion_pairing_timeseries", timeseries_figure))
    for stem, figure in figures:
        saved.extend(save_figure(figure, analysis_dir, stem, formats, args.dpi))
        plt.close(figure)

    plot_manifest = {
        "command": "plot_ion_pairing.py",
        "case_label": case_label,
        "analysis_directory": str(analysis_dir),
        "primary_cutoff_nm": cutoff_nm,
        "detected_na_p_minimum_nm": detected_minimum_nm,
        "timeseries_moving_average_frames": moving_window,
        "formats": formats,
        "dpi": args.dpi,
        "inputs": [
            "rdf_coordination_Na_P.csv",
            "rdf_coordination_Na_F.csv",
            "ion_pairing_summary.csv",
            "ion_pairing_timeseries.csv",
            "analysis_manifest.json",
        ],
        "outputs": [path.name for path in saved],
    }
    plot_manifest_path.write_text(
        json.dumps(plot_manifest, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"Graphs complete: {analysis_dir}")
    for path in saved:
        print(f"  {path.name}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except PlotError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        raise SystemExit(2)
